# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    golang: "1.22"
    python: "3.11"
  jobs:
    pre_install:
      - cd doc && python3 .sphinx/build_requirements.py
      - git fetch --unshallow || true
    pre_build:
      - cd doc && python3 .sphinx/download-docs.py
      - pwd
      - ls doc -l
      - cd doc/.sphinx/deps/lxd/ && make doc BUILDDIR=$READTHEDOCS_OUTPUT/html/lxd
      - cd doc/microceph-docs && make .sphinx/venv
      - cd doc/microceph-docs && .sphinx/venv/bin/activate; sphinx-build -b dirhtml . "$READTHEDOCS_OUTPUT/html/microceph"
      - ls - R $READTHEDOCS_OUTPUT
    post_build:
      - ls $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: doc/conf.py
  fail_on_warning: true

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/.sphinx/requirements.txt
