# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    golang: "1.22"
    python: "3.11"
  commands:
      - git fetch --unshallow || true
      - pip install gitpython
      - cd doc && python3 .sphinx/download-docs.py
      - pwd
      - ls doc -l
      - cd doc/.sphinx/deps/lxd/ && go build -ldflags "-s -w" -o trimpath -o lxc.bin ./lxc
      - cd doc/.sphinx/deps/lxd/ && git fetch --unshallow || true
      - cd doc/lxd-docs/doc && make -f Makefile.sp sp-html BUILDDIR=$READTHEDOCS_OUTPUT/html/lxd LOCAL_SPHINX_BUILD=False ADDPREREQS="gitpython pyyaml"
      - ls doc -l
      # Pretend that woke is installed - we don't need it for building
      - ln -s /bin/sh doc/microceph-docs/woke
      - ln -s /bin/sh doc/microovn-docs/woke
      - cd doc/microceph-docs && make html BUILDDIR=$READTHEDOCS_OUTPUT/html/microceph PATH=$PATH:.
      - cd doc/microovn-docs && make html BUILDDIR=$READTHEDOCS_OUTPUT/html/microovn PATH=$PATH:.
      - ls -R $READTHEDOCS_OUTPUT
      - cd doc && make html BUILDDIR=$READTHEDOCS_OUTPUT/html/microcloud
      - ls -R $READTHEDOCS_OUTPUT

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: doc/conf.py
  fail_on_warning: true

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/.sphinx/requirements.txt
